Examen2/examen2/examen2/core/urls.py
from django.urls import path
from core import views

app_name = "core"
urlpatterns = [
    path('estadios/',views.Estadio.as_view(), name="estadios"),
    path('create/estadio/',views.CreateEstadio.as_view(), name="create_estadio"),
    path('recover/estadio/<int:pk>/', views.DetailEstadio.as_view(), name= "recover_estadio"),
    path('update/estadio/<int:pk>/', views.UpdateEstadio.as_view(), name= "update_estadio"),
    path('delete/estadio/<int:pk>/', views.DeleteEstadio.as_view(), name= "delete_estadio"),
    
    path('equipos/',views.Equipo.as_view(), name="equipos"),
    path('create/equipo/',views.CreateEquipos.as_view(), name="create_equipo"),
    path('recover/equipo/<int:pk>/', views.DetailEquipos.as_view(), name= "recover_equipo"),
    path('update/equipo/<int:pk>/', views.UpdateEquipos.as_view(), name= "update_equipo"),
    path('delete/equipo/<int:pk>/', views.DeleteEquipos.as_view(), name= "delete_equipo"),

    path('ciudades/',views.Ciudad.as_view(), name="ciudades"),
    path('create/ciudad/',views.Createcuidad.as_view(), name="create_ciudad"),
    path('recover/ciudad/<int:pk>/', views.Detailciudad.as_view(), name= "recover_ciudad"),
    path('update/ciudad/<int:pk>/', views.Updateciudad.as_view(), name= "update_ciudad"),
    path('delete/ciudad/<int:pk>/', views.Deleteciudad.as_view(), name= "delete_ciudad"),
]

Examen2/examen2/examen2/examen2nfl/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('core.urls'))
]

Examen2/examen2/examen2/home/urls.py
from django.urls import path, include
from home import views

app_name="home"
urlpatterns = [
   path('', views.home.as_view(),name='home') 
]

Examen2/examen2/examen2/core/models.py
from django.db import models

# Create your models here.


class Ciudades(models.Model):
    Nombre = models.CharField(max_length=35, default= "Houston")
    def __str__(self):
        return self.Nombre

class Equipos(models.Model):
    Nombre = models.CharField(max_length=35, default= "Beers")
    Ciudad = models.ForeignKey(Ciudades, on_delete=models.CASCADE)
    def __str__(self):
        return self.Nombre

class Estadios(models.Model):
    Nombre = models.CharField(max_length=35, default= "Raymond James Stadium")
    Equipos= models.ForeignKey(Equipos, on_delete=models.CASCADE)
    def __str__(self):
        return self.Nombre

Examen2/examen2/examen2/home/models.py
from django.db import models

# Create your models here.

from django.urls import path, include
from home import views

app_name="home"
urlpatterns = [
   path('', views.home.as_view(),name='home') 
]

Examen2/examen2/examen2/core/forms.py
from django import forms
from .models import *

##FORM PARA ESTADIOS

class NewEstadioForms(forms.ModelForm):
    class Meta:
        model = Estadios
        fields = "__all__"
        widgets = {
            "Nombre": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre de la ciudad"}),
            "Equipos": forms.Select(attrs={"class":"form-select form-control"}),
            }



class UpdateEstadioForms(forms.ModelForm):
    class Meta:
        model = Estadios
        fields = "__all__"
        widgets = {
            "Nombre": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre de la ciudad"}),
            "Equipos": forms.Select(attrs={"class":"form-select form-control"}),
            }

##FORMS PARA EQUIPOS

class NewEquipoForms(forms.ModelForm):
    class Meta:
        model = Equipos
        fields = "__all__"
        widgets = {
            "Nombre": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre de la ciudad"}),
            "Ciudad": forms.Select(attrs={"class":"form-select form-control"}),
            }
        
class UpdateEquipoForms(forms.ModelForm):
    class Meta:
        model = Equipos
        fields = "__all__"
        widgets = {
            "Nombre": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre de la ciudad"}),
            "Ciudad": forms.Select(attrs={"class":"form-select form-control"}),
            }

##FORMS PARA CIUDADES

class NewCiudadForms(forms.ModelForm):
    class Meta:
        model = Ciudades
        fields = "__all__"
        widgets = {
            "Nombre": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre de la ciudad"}),
            }

class UpdateCiudadForms(forms.ModelForm):
    class Meta:
        model = Ciudades
        fields = "__all__"
        widgets = {
            "Nombre": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre de la ciudad"}),
            }

Examen2/examen2/examen2/core/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from .models import *
from .forms import *

# Create your views here.




##CRUD ESTADIOS

class Estadio(generic.View):
    template_name = "core/estadios/estadio.html"
    context = {}

    def get(self, request, *args, **kwargs):
        Estadio = Estadios.objects.all()
        self.context = {
            "Estadios": Estadio
        }
        return render(request, self.template_name,self.context)

class DetailEstadio(generic.DetailView):
    template_name = "core/estadios/recover_estadio.html"
    model = Estadios

class CreateEstadio(generic.CreateView):
    template_name = "core/estadios/create_estadio.html"
    model = Estadios
    form_class = NewEstadioForms
    success_url = reverse_lazy("core:estadios")

class UpdateEstadio(generic.UpdateView):
    template_name = "core/estadios/update_estadio.html"
    model = Estadios
    form_class = UpdateEstadioForms
    success_url = reverse_lazy("core:estadios")

class DeleteEstadio(generic.DeleteView):
    template_name = "core/estadios/delete_estadio.html"
    model = Estadios
    success_url = reverse_lazy("core:estadios")




##CRUD EQUIPOS

class Equipo(generic.View):
    template_name = "core/equipos/equipo.html"
    context = {}

    def get(self, request, *args, **kwargs):
        equipo =  Equipos.objects.all()
        self.context = {
            "Equipos": equipo
        }
        return render(request, self.template_name,self.context)
    
class CreateEquipos(generic.CreateView):
    template_name = "core/equipos/create_equipo.html"
    model = Equipos
    form_class = NewEquipoForms
    success_url = reverse_lazy("core:equipos")

class DetailEquipos(generic.DetailView):
    template_name = "core/equipos/recover_equipo.html"
    model = Equipos

class UpdateEquipos(generic.UpdateView):
    template_name = "core/equipos/update_equipo.html"
    model = Equipos
    form_class = UpdateEquipoForms
    success_url = reverse_lazy("core:equipos")

class DeleteEquipos(generic.DeleteView):
    template_name = "core/equipos/delete_equipo.html"
    model = Equipos
    success_url = reverse_lazy("core:equipos")



##CRUD CIUDADES

class Ciudad(generic.View):
    template_name = "core/ciudades/ciudad.html"
    context = {}

    def get(self, request, *args, **kwargs):
        Ciudad = Ciudades.objects.all()
        self.context = {
            "Ciudades": Ciudad
        }
        return render(request, self.template_name,self.context)

class Createcuidad(generic.CreateView):
    template_name = "core/ciudades/create_ciudad.html"
    model = Ciudades
    form_class = NewCiudadForms
    success_url = reverse_lazy("core:ciudades")

class Detailciudad(generic.DetailView):
    template_name = "core/ciudades/recover_ciudad.html"
    model = Ciudades

class Updateciudad(generic.UpdateView):
    template_name = "core/ciudades/update_ciudad.html"
    model = Ciudades
    form_class = UpdateCiudadForms
    success_url = reverse_lazy("core:ciudades")

class Deleteciudad(generic.DeleteView):
    template_name = "core/ciudades/delete_ciudad.html"
    model = Ciudades
    success_url = reverse_lazy("core:ciudades")
 

Examen2/examen2/examen2/home/views.py
from django.shortcuts import render
from django.views import generic

# Create your views here.


class home(generic.View):
    template_name = "home/home.html"
    context={}
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.context)

Examen2/examen2/examen2/templates/core/equipos/create_equipo.html
{% extends "base/base.html" %}

{% block title %}
CREATE NEW TEAM
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-success">Create Team</button>
        <a href="{% url 'core:equipos' %}" class="btn btn-outline-warning">Cancel</a>
    </form>
{% endblock content %}  

Examen2/examen2/examen2/templates/core/equipos/delete_equipo.html
{% extends "base/base.html" %}

{% block title %}
DELETE TEAM 
{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        ¿Deseas borrar: {{ object.Nombre }}?
        <button type="submit" class="btn btn-outline-danger">Delete Team</button>
        <a href="{% url 'core:equipos' %}" class="btn btn-outline-warning">Cancel</a>
    </form>
{% endblock content %}

Examen2/examen2/examen2/templates/core/equipos/equipo.html
{% extends 'base/base.html' %}

{% block title %} 
TEAMS
{% endblock title %}

{% block content %}


    <a href="{% url 'core:create_equipo' %}" class="btn btn-outline-success form-control">New Team</a>
    <table class="table table-striped table-hover">
        <thead>
            <th>ID</th>
            <th>NAME</th>
            <th></th>
            <th>ACTIONS</th>
            <th></th>

        </thead>
        <tbody>
            {% for Equipos in Equipos %}
                <tr>
                    <td>{{ Equipos.id }}</td>
                    <td>{{ Equipos.Nombre }}</td>
                    <td><a href="{% url 'core:recover_equipo' Equipos.id %}" class="btn btn-outline-info"> Details </a></td>
                    <td><a href="{% url 'core:update_equipo' Equipos.id %}" class="btn btn-outline-warning"> Update</a></td>
                    <td><a href="{% url 'core:delete_equipo' Equipos.id %}" class="btn btn-outline-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
   
{% endblock content %}

Examen2/examen2/examen2/templates/core/equipos/recover_equipo.html
{% extends "base/base.html" %}

{% block title %}
DETAILS TEAM 
{% endblock title %}


{% block content %}
<h1>Name: </h1>{{ object.Nombre }}
<br>
<h1>City: </h1>{{ object.Ciudad }}
<br>
  <a href="{% url 'core:equipos' %}">Back</a>
{% endblock content %}

Examen2/examen2/examen2/templates/core/equipos/update_equipo.html
{% extends "base/base.html" %}

{% block title %}
UPDATE TEAM
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-primary">Update Team</button>
        <a href="{% url 'core:equipos' %}" class="btn btn-outline-warning">Cancel</a>
    </form>
{% endblock content %}

Examen2/examen2/examen2/templates/home/home.html
{% extends "base/base.html" %}
{% block title %} HOME {% endblock title %}

{%block content%}
{%endblock content%}